<?php

namespace IMIE\IMIEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends EntityRepository
{
}
