<?php

namespace IMIE\IMIEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigneCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneCommandeRepository extends EntityRepository{
	public function findCommandes(){
		$qb=$this->createQueryBuilder('l');
		$qb->leftjoin('l.commande','c')
			->join('c.client','clt')
			->join('l.article','a');
		$qb->select('c.id,c.dateCommande,clt.code,clt.nom,clt.adresse,
		sum(l.quantite*a.prixUnitaire) as montant')
		->groupBy('c.id')
		->orderBy('c.id','desc');
		return $qb->getQuery()->getResult();
	}
	
}
