<?php

namespace IMIE\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HierarchieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HierarchieRepository extends EntityRepository
{
}
