user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

imie:
    resource: "@IMIEBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
