security:
    encoders:
        IMIE\UserBundle\Entity\User: 
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false            
       
    providers:
        in_entity:
            entity: {class: IMIE\UserBundle\Entity\User, property: username}

    firewalls:

        main:
            pattern:   ^/
            anonymous: true        
            provider: in_entity
            form_login:
                login_path: user_login
                check_path: login_check
            logout: 
                path: logout
                target: /

    access_control:
        # - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
