services:
#    imie.example:
#        class: IMIE\IMIEBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     imie.fct:
       class: IMIE\IMIEBundle\FCT\IMIEFonction
       arguments: []
     imie.extra:
       class: IMIE\IMIEBundle\Extra\ExtraFonction
       arguments: []       